### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by cjtcxh** [autopilot-rs/autopy#16]
```
import autopy

def hello_world():
    autopy.alert.alert("Hello, world")
hello_world()
```
Traceback (most recent call last):
...
  File "E:\tools\Python2.7\lib\site-packages\autopy\__init__.py", line 6, in <module>
    import alert, bitmap, color, key, mouse, screen
ImportError: dynamic module does not define init function (initalert)

Does anyone know what it is going on?

**Comment by HolmstN** [comment]
I'm having a similar issue but with Python 3.7:

```
 import autopy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\nholmstedt\AppData\Local\Programs\Python\Python37\lib\site-packages\autopy\__init__.py", line 6, in <module>
    from . import alert, bitmap, color, key, mouse, screen
ImportError: dynamic module does not define module export function (PyInit_alert)
```

**Comment by msanders** [comment]
Hmm, I'm not sure what's going on here. Is this after installing via pip?

**Comment by msanders** [comment]
Closing due to inactivity. Please re-open if this is still happening on the latest version.
