### ISSUE TITLE
AutoPy Not installing

### ISSUE THREAD

**Issue by ArvindSami** [autopilot-rs/autopy#37]
Got the follow error message. Using a raspberrry pi with buster

pi@raspberrypi:~ $ pip install -U autopy
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting autopy
  Using cached https://files.pythonhosted.org/packages/d8/6d/bbc9381ef2e674bf512e6988c169a348d19f23d0038c7004ca4238e6712e/autopy-3.0.0.tar.gz
Building wheels for collected packages: autopy
  Building wheel for autopy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-LUKlaj/autopy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-LUKlaj/autopy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-EgpjLy --python-tag cp27
       cwd: /tmp/pip-install-LUKlaj/autopy/
  Complete output (55 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/autopy
  copying autopy/__init__.py -> build/lib.linux-armv7l-2.7/autopy
  running build_ext
  running build_rust
      Updating crates.io index
  error: failed to load source for a dependency on `autopilot`
  
  Caused by:
    Unable to update registry `https://github.com/rust-lang/crates.io-index`
  
  Caused by:
    failed to fetch `https://github.com/rust-lang/crates.io-index`
  
  Caused by:
    SSL error: received early EOF; class=Ssl (16)
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-LUKlaj/autopy/setup.py", line 112, in <module>
      main()
    File "/tmp/pip-install-LUKlaj/autopy/setup.py", line 107, in main
      zip_safe=False,  # Rust extensions are not zip safe, like C-extensions.
    File "/home/pi/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/dist-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
      self.run_command(cmd_name)
    File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
      cmd_obj.run()
    File "/home/pi/.local/lib/python2.7/site-packages/setuptools_rust/build_ext.py", line 26, in run
      build_rust.run()
    File "/home/pi/.local/lib/python2.7/site-packages/setuptools_rust/build.py", line 313, in run
      self.build_extension(ext)
    File "/home/pi/.local/lib/python2.7/site-packages/setuptools_rust/build.py", line 95, in build_extension
      metadata = json.loads(check_output(metadata_command).decode("utf-8"))
    File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
      raise CalledProcessError(retcode, cmd, output=output)
  subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101
  ----------------------------------------
  ERROR: Failed building wheel for autopy
  Running setup.py clean for autopy
Failed to build autopy
Installing collected packages: autopy
  Running setup.py install for autopy ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-LUKlaj/autopy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-LUKlaj/autopy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pceivA/install-record.txt --single-version-externally-managed --compile
         cwd: /tmp/pip-install-LUKlaj/autopy/
    Complete output (57 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-2.7
    creating build/lib.linux-armv7l-2.7/autopy
    copying autopy/__init__.py -> build/lib.linux-armv7l-2.7/autopy
    running build_ext
    running build_rust
        Updating crates.io index
    error: failed to load source for a dependency on `autopilot`
    
    Caused by:
      Unable to update registry `https://github.com/rust-lang/crates.io-index`
    
    Caused by:
      failed to fetch `https://github.com/rust-lang/crates.io-index`
    
    Caused by:
      SSL error: received early EOF; class=Ssl (16)
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-LUKlaj/autopy/setup.py", line 112, in <module>
        main()
      File "/tmp/pip-install-LUKlaj/autopy/setup.py", line 107, in main
        zip_safe=False,  # Rust extensions are not zip safe, like C-extensions.
      File "/home/pi/.local/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/pi/.local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run
        self.run_command('build')
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run
        self.run_command(cmd_name)
      File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/pi/.local/lib/python2.7/site-packages/setuptools_rust/build_ext.py", line 26, in run
        build_rust.run()
      File "/home/pi/.local/lib/python2.7/site-packages/setuptools_rust/build.py", line 313, in run
        self.build_extension(ext)
      File "/home/pi/.local/lib/python2.7/site-packages/setuptools_rust/build.py", line 95, in build_extension
        metadata = json.loads(check_output(metadata_command).decode("utf-8"))
      File "/usr/lib/python2.7/subprocess.py", line 223, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['cargo', 'metadata', '--manifest-path', 'Cargo.toml', '--format-version', '1']' returned non-zero exit status 101
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-LUKlaj/autopy/setup.py'"'"'; __file__='"'"'/tmp/pip-install-LUKlaj/autopy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-pceivA/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

Any helpa pp

**Comment by msanders** [comment]
Is connectivity working? Looks like it's failing to fetch from GitHub.

**Comment by ArvindSami** [comment]
Yes, everything else is working. I can browse the internet. The git clone method works for everything else. apt-get etc all works,I managed to install keyboard via pip method.

**Comment by anonymousminati** [comment]
I am also getting the same error to install autopsy in pycharm...can you help me, please. I am a student and learning python. I have a project from my college to be complete and the autopy is giving me an error. please, solve this.

**Comment by ramik10** [comment]
I am also getting the same error it would be great if you fix it

**Comment by anonymousminati** [comment]
@ramik10 sorry brother i tried to hard..i think any expert who has this problem can solve ..or anyone who can have autoPY package install must share with us by uploading

**Comment by CoderZ90** [comment]
I am also getting this problem how to solve it

**Comment by CoderZ90** [comment]
Why is he not fixing it ?

**Comment by mayeskhatri243** [comment]
I'm also getting same error how to solve it. 

#help

**Comment by pevogam** [comment]
We will no longer support Python 2 so I am closing this issue.
