### ISSUE TITLE
ImportError: DLL load failed: %1 is not a valid Win32 application.

### ISSUE THREAD

**Issue by EinoVirtanen** [autopilot-rs/autopy#5]
I just installed a fresh Windows 10, Python 2.7 and did 'pip install autopy' and now I can't import it.

_C:\Users\asd\GhoulPro>python main.py
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    import autopy
  File "C:\Python27\lib\site-packages\autopy\__init__.py", line 6, in <module>
    from . import alert, bitmap, color, key, mouse, screen
ImportError: DLL load failed: %1 is not a valid Win32 application._

What should I do? Is this a case of pebkac or is there something wrong?

**Comment by msanders** [comment]
This may be an issue with the binary wheel distribution. Does it work for you if you install on Python 3 (or from source)?

**Comment by EinoVirtanen** [comment]
Python3 pip can't install autopy, and building manually gives the following output:

C:\Users\foo bar>pip install -U autopy
Collecting autopy
  Using cached https://files.pythonhosted.org/packages/cb/99/9203ea5442f3bd52695fce191305eeb6de63ff29a9a05d0c5ecb60ec4a69/autopy-1.0.1.tar.gz
Installing collected packages: autopy
  Running setup.py install for autopy ... error
    Complete output from command "c:\users\foo bar\appdata\local\programs\python\python36-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\fooVI~1\\AppData\\Local\\Temp\\pip-install-a8syyfvm\\autopy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\fooVI~1\AppData\Local\Temp\pip-record-9w0cu0sn\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-3.6
    creating build\lib.win32-3.6\autopy
    copying autopy\__init__.py -> build\lib.win32-3.6\autopy
    running build_ext
    running build_rust
    cargo rustc --lib --manifest-path Cargo.toml --features pyo3/extension-module pyo3/python3 --release -- --crate-type cdylib
        Updating registry `https://github.com/rust-lang/crates.io-index`
     Downloading image v0.19.0
     Downloading either v1.5.0
     Downloading autopilot v0.1.1
     Downloading pyo3 v0.2.6
     Downloading gif v0.10.0
     Downloading lzw v0.10.0
     Downloading num-rational v0.1.42
     Downloading png v0.12.0
     Downloading num-traits v0.2.2
     Downloading num-derive v0.2.0
     Downloading jpeg-decoder v0.1.14
     Downloading scoped_threadpool v0.1.9
     Downloading byteorder v1.2.2
     Downloading num-iter v0.1.35
     Downloading color_quant v1.0.0
     Downloading num-integer v0.1.36
     Downloading inflate v0.4.2
     Downloading deflate v0.7.18
     Downloading bitflags v1.0.2
     Downloading adler32 v1.0.2
     Downloading syn v0.12.15
     Downloading proc-macro2 v0.2.3
     Downloading quote v0.4.2
     Downloading unicode-xid v0.1.0
     Downloading rayon v1.0.1
     Downloading rayon-core v1.4.0
     Downloading rand v0.4.2
     Downloading libc v0.2.40
     Downloading num_cpus v1.8.0
     Downloading lazy_static v1.0.0
     Downloading crossbeam-deque v0.2.0
     Downloading winapi v0.3.4
     Downloading crossbeam-epoch v0.3.1
     Downloading crossbeam-utils v0.2.2
     Downloading arrayvec v0.4.7
     Downloading memoffset v0.2.1
     Downloading cfg-if v0.1.2
     Downloading scopeguard v0.3.3
     Downloading nodrop v0.1.12
     Downloading pkg-config v0.3.11
     Downloading log v0.4.1
     Downloading spin v0.4.8
     Downloading pyo3cls v0.2.1
     Downloading syn v0.11.11
     Downloading log v0.3.9
     Downloading quote v0.3.15
     Downloading unicode-xid v0.0.4
     Downloading synom v0.11.3
     Downloading version_check v0.1.3
     Downloading regex v0.2.10
     Downloading utf8-ranges v1.0.0
     Downloading thread_local v0.3.5
     Downloading regex-syntax v0.5.5
     Downloading aho-corasick v0.6.4
     Downloading memchr v2.0.1
     Downloading unreachable v1.0.0
     Downloading void v1.0.2
     Downloading ucd-util v0.1.1
       Compiling cfg-if v0.1.2
       Compiling nodrop v0.1.12
       Compiling winapi v0.3.4
       Compiling scopeguard v0.3.3
       Compiling memoffset v0.2.1
       Compiling lazy_static v1.0.0
       Compiling void v1.0.2
       Compiling libc v0.2.40
       Compiling unicode-xid v0.1.0
       Compiling rayon-core v1.4.0
       Compiling ucd-util v0.1.1
    error: linker `link.exe` not found
      |
      = note: The system cannot find the file specified. (os error 2)

    note: the msvc targets depend on the msvc linker but `link.exe` was not found

    note: please ensure that VS 2013 or VS 2015 was installed with the Visual C++ option

    error: aborting due to previous error

    error: Could not compile `rayon-core`.
    warning: build failed, waiting for other jobs to finish...
    error: linker `link.exe` not found
      |
      = note: The system cannot find the file specified. (os error 2)

    note: the msvc targets depend on the msvc linker but `link.exe` was not found

    note: please ensure that VS 2013 or VS 2015 was installed with the Visual C++ option

    error: aborting due to previous error

    error: Could not compile `winapi`.

    To learn more, run the command again with --verbose.
    error: cargo failed with code: 101


    ----------------------------------------
Command ""c:\users\foo bar\appdata\local\programs\python\python36-32\python.exe" -u -c "import setuptools, tokenize;__file__='C:\\Users\\fooVI~1\\AppData\\Local\\Temp\\pip-install-a8syyfvm\\autopy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\fooVI~1\AppData\Local\Temp\pip-record-9w0cu0sn\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\fooVI~1\AppData\Local\Temp\pip-install-a8syyfvm\autopy\

**Comment by msanders** [comment]
Closing due to inactivity.
