### ISSUE TITLE
Autopy is not installing

### ISSUE THREAD

**Issue by CoderZ90** [autopilot-rs/autopy#78]
I am trying to install autopy but it is not installing i dont whats the problem

**Comment by Urmila17** [comment]
Kindly share the error

**Comment by TanishqSinghAnand** [comment]
Facing the same issue ! It says that it is unable to build the wheel and gives a huge error of about 1000 lines
Python version - 3.9.5
Rustup nightly version - 2019-10-05
Thanks

**Comment by TanishqSinghAnand** [comment]
I tried to install it in python 3.7.0 and it worked fine but it is still not able to install it in python 3.9.5

**Comment by Urmila17** [comment]
autopy does not support python above 9 so downgrade , it will work. With the current release of 3.9.1+, not all features have been upgraded. Move all your code that used to utilize this tool to "pyautogui" which enables the same functionality for keyboard and mouse manipulation through python.

**Comment by TanishqSinghAnand** [comment]
Okay thank you

**Comment by IBims1ckoky** [comment]
When i try to install autopy i get this error?

`Collecting autopy==4.0.0
  Using cached autopy-4.0.0.tar.gz (20 kB)

    ERROR: Command errored out with exit status 1:
     command: 'F:\PyCharmProjects\VirtualMouseAI\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\maxia\\AppData\\Local\\Temp\\pip-install-bc05paqq\\autopy_a61a6f8060e84428abc5254903e33bb2\\setup.py'"'"'; __file__='"'"'C:\\Users\\maxia\\AppData\\Local\\Temp\\pip-install-bc05paqq\\autopy_a61a6f8060e84428abc5254903e33bb2\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\maxia\AppData\Local\Temp\pip-pip-egg-info-6djyb16q'
         cwd: C:\Users\maxia\AppData\Local\Temp\pip-install-bc05paqq\autopy_a61a6f8060e84428abc5254903e33bb2\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\maxia\AppData\Local\Temp\pip-install-bc05paqq\autopy_a61a6f8060e84428abc5254903e33bb2\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3d/3e/e589bfe03c7ee1c3d832dda10b908557f25a09d66acfc8fc7d982ee23d1a/autopy-4.0.0.tar.gz#sha256=b889dc1245426aa06769d3d87df0d96904ca729d0e9441a0096aa3ae9fbae43f (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement autopy==4.0.0 (from versions: 0.5, 0.51, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 4.0.0)
ERROR: No matching distribution found for autopy==4.0.0
WARNING: You are using pip version 21.1.2; however, version 21.2.1 is available.
You should consider upgrading via the 'F:\PyCharmProjects\VirtualMouseAI\venv\Scripts\python.exe -m pip install --upgrade pip' command.`

**Comment by IBims1ckoky** [comment]
When i try to install autopy i get this error:


Collecting autopy==4.0.0
  Using cached autopy-4.0.0.tar.gz (20 kB)

    ERROR: Command errored out with exit status 1:
     command: 'F:\PyCharmProjects\VirtualMouseAI\venv\Scripts\python.exe' -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\maxia\\AppData\\Local\\Temp\\pip-install-bc05paqq\\autopy_a61a6f8060e84428abc5254903e33bb2\\setup.py'"'"'; __file__='"'"'C:\\Users\\maxia\\AppData\\Local\\Temp\\pip-install-bc05paqq\\autopy_a61a6f8060e84428abc5254903e33bb2\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\maxia\AppData\Local\Temp\pip-pip-egg-info-6djyb16q'
         cwd: C:\Users\maxia\AppData\Local\Temp\pip-install-bc05paqq\autopy_a61a6f8060e84428abc5254903e33bb2\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\maxia\AppData\Local\Temp\pip-install-bc05paqq\autopy_a61a6f8060e84428abc5254903e33bb2\setup.py", line 8, in <module>
        from setuptools_rust import Binding, RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/3d/3e/e589bfe03c7ee1c3d832dda10b908557f25a09d66acfc8fc7d982ee23d1a/autopy-4.0.0.tar.gz#sha256=b889dc1245426aa06769d3d87df0d96904ca729d0e9441a0096aa3ae9fbae43f (from https://pypi.org/simple/autopy/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement autopy==4.0.0 (from versions: 0.5, 0.51, 1.0.0, 1.0.1, 1.1.0, 1.1.1, 2.0.0, 2.1.0, 3.0.0, 3.0.1, 3.1.0, 4.0.0)
ERROR: No matching distribution found for autopy==4.0.0
WARNING: You are using pip version 21.1.2; however, version 21.2.1 is available.
You should consider upgrading via the 'F:\PyCharmProjects\VirtualMouseAI\venv\Scripts\python.exe -m pip install --upgrade pip' command.

**Comment by pevogam** [comment]
Could you try this with a wheel for your platform among these build artifacts?

https://github.com/autopilot-rs/autopy/actions/runs/14040870872
