### ISSUE TITLE
can't install autopy,why it's so difficulty while I just try to install a python library

### ISSUE THREAD

**Issue by wqtb** [autopilot-rs/autopy#85]
nightly-x86_64-pc-windows-msvc installed - rustc 1.58.0-nightly (d914f17ca 2021-11-16)

error: invalid toolchain name: '2019-10-05'

**Comment by wqtb** [comment]
I have installed rust and vc++2019 ,but after I typed  'rustup install nightly 2019-10-05 --force' ,I got an error like I post

**Comment by Guuri11** [comment]
same here, did you figure it out how to solve it?

**Comment by wqtb** [comment]
> same here, did you figure it out how to solve it?

unfortunately not, I have no idea about how to address this issue, hope you can solve it

**Comment by GaxbiCodes** [comment]
Same with me... bro what's happening man...

**Comment by wqtb** [comment]
> 

I have no idea

**Comment by SARTHxJAIN** [comment]
> nightly-x86_64-pc-windows-msvc installed - rustc 1.58.0-nightly (d914f17ca 2021-11-16)
> 
> error: invalid toolchain name: '2019-10-05'

same problem

**Comment by wqtb** [comment]
I changed another computer, which   python  version is **3.8.10** ,Autopy installed success

**Comment by wqtb** [comment]
PS C:\Users\Administrator> python --version
Python 3.8.10
PS C:\Users\Administrator> pip install autopy
Collecting autopy
  Downloading autopy-4.0.0-cp38-cp38-win_amd64.whl (3.7 MB)
     |████████████████████████████████| 3.7 MB 211 kB/s
Installing collected packages: autopy
Successfully installed autopy-4.0.0

**Comment by Taylorzing** [comment]
C:\Users\chens>pip install -U autopy
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/, https://pypi.tuna.tsinghua.edu.cn/simple/, https://pypi.mirrors.ustc.edu.cn/simple/, https://pypi.douban.com/simple/
Collecting autopy
  Using cached https://pypi.doubanio.com/packages/3d/3e/e589bfe03c7ee1c3d832dda10b908557f25a09d66acfc8fc7d982ee23d1a/autopy-4.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: autopy
  Building wheel for autopy (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]

**Comment by Taylorzing** [comment]
note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> autopy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Taylorzing** [comment]
failed to load source for dependency `autopilot`

      Caused by:
        Unable to update registry `crates-io`

      Caused by:
        failed to fetch `https://github.com/rust-lang/crates.io-index`

      Caused by:
        failed to send request: 鎿嶄綔瓒呮椂
        ; class=Os (2)
      error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module -- --crate-type cdylib` failed with code 101
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> autopy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

C:\Users\chens>
C:\Users\chens>pip install autopy
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/, https://pypi.tuna.tsinghua.edu.cn/simple/, https://pypi.mirrors.ustc.edu.cn/simple/, https://pypi.douban.com/simple/
Collecting autopy
  Using cached https://pypi.doubanio.com/packages/3d/3e/e589bfe03c7ee1c3d832dda10b908557f25a09d66acfc8fc7d982ee23d1a/autopy-4.0.0.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: autopy
  Building wheel for autopy (setup.py) ... canceled
ERROR: Operation cancelled by user

C:\Users\chens>
C:\Users\chens> rustup default nightly-2019-10-05
info: syncing channel updates for 'nightly-2019-10-05-x86_64-pc-windows-msvc'
info: latest update on 2019-10-05, rust version 1.40.0-nightly (2e7244807 2019-10-04)
error: some components unavailable for download for channel 'nightly-2019-10-05': 'clippy' for target 'x86_64-pc-windows-msvc', 'rustfmt' for target 'x86_64-pc-windows-msvc'Sometimes not all components are available in any given nightly. If you don't need the components, you could try a minimal installation with:

    rustup toolchain add nightly-2019-10-05 --profile minimal

C:\Users\chens>rustup toolchain add nightly-2019-10-05 --profile minimal
info: syncing channel updates for 'nightly-2019-10-05-x86_64-pc-windows-msvc'
info: latest update on 2019-10-05, rust version 1.40.0-nightly (2e7244807 2019-10-04)
info: downloading component 'cargo'
  3.1 MiB /   3.1 MiB (100 %)   1.3 MiB/s in  2s ETA:  0s
info: downloading component 'rust-std'
176.9 MiB / 176.9 MiB (100 %)   7.1 MiB/s in 27s ETA:  0s
info: downloading component 'rustc'
 41.3 MiB /  41.3 MiB (100 %)   7.4 MiB/s in  7s ETA:  0s
info: installing component 'cargo'
info: installing component 'rust-std'
176.9 MiB / 176.9 MiB (100 %)  31.4 MiB/s in  6s ETA:  0s
info: installing component 'rustc'
 41.3 MiB /  41.3 MiB (100 %)  14.7 MiB/s in  2s ETA:  0s

  nightly-2019-10-05-x86_64-pc-windows-msvc installed - rustc 1.40.0-nightly (2e7244807 2019-10-04)

info: checking for self-updates

**Comment by Taylorzing** [comment]
Caused by:
        process didn't exit successfully: `rustc --crate-name build_script_build --edition=2018 C:\Users\chens\.cargo\registry\src\github.com-1ecc6299db9ec823\proc-macro2-1.0.46\build.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debug-assertions=off --cfg "feature=\"default\"" --cfg "feature=\"proc-macro\"" -C metadata=19e068e4740c710a -C extra-filename=-19e068e4740c710a --out-dir C:\Users\chens\AppData\Local\Temp\pip-install-c_v259j5\autopy_dde13795bf234956bef42826d1284ec4\target\release\build\proc-macro2-19e068e4740c710a -L dependency=C:\Users\chens\AppData\Local\Temp\pip-install-c_v259j5\autopy_dde13795bf234956bef42826d1284ec4\target\release\deps --cap-lints allow` (exit code: 1)
      error: `cargo rustc --lib --message-format=json-render-diagnostics --manifest-path Cargo.toml --release -v --features pyo3/extension-module -- --crate-type cdylib` failed with code 101
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> autopy

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by Taylorzing** [comment]
why was so hard to pip install autopy

**Comment by Taylorzing** [comment]
i found way to solve it for  two days . only python3.8 can do it

**Comment by Meishe91** [comment]
> i found way to solve it for two days . only python3.8 can do it

Was running into this. Can confirm that downgrading to python3.8 did work.

**Comment by josephT273** [comment]
```bash
PS C:\Users\Joseph Tadesse\PycharmProjects\AdvancedComputerVision> pip install autopy
Collecting autopy
  Downloading autopy-4.0.0.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Joseph Tadesse\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Joseph Tadesse\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Joseph Tadesse\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-qo759ua3\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-qo759ua3\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-qo759ua3\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-qo759ua3\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'setuptools_rust'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\Joseph Tadesse\PycharmProjects\AdvancedComputerVision> pip install autopy
Collecting autopy
  Using cached autopy-4.0.0.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Joseph Tadesse\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Joseph Tadesse\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Joseph Tadesse\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-0vhe60wr\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-0vhe60wr\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-0vhe60wr\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
PS C:\Users\Joseph Tadesse\PycharmProjects\AdvancedComputerVision> pip install autopy
Collecting autopy
  Using cached autopy-4.0.0.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Joseph Tadesse\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\Joseph Tadesse\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\Joseph Tadesse\AppData\Local\Programs\Python\Python310\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-1y0w_5qp\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-1y0w_5qp\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-1y0w_5qp\overlay\Lib\site-packages\setuptools\build_meta.py", line 487, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\Joseph Tadesse\AppData\Local\Temp\pip-build-env-1y0w_5qp\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'setuptools_rust'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\Users\Joseph Tadesse\PycharmProjects\AdvancedComputerVision>
```
