### ISSUE TITLE
Does not work on Sonoma 14.5 and Python 3.12

### ISSUE THREAD

**Issue by ni-dschiller** [autopilot-rs/autopy#99]
```shell
Collecting pedalboard (from -r requirements.txt (line 1))
  Using cached pedalboard-0.9.6-cp312-cp312-macosx_11_0_arm64.whl.metadata (16 kB)
Collecting mido (from -r requirements.txt (line 2))
  Using cached mido-1.3.2-py3-none-any.whl.metadata (6.4 kB)
Collecting pyautogui (from -r requirements.txt (line 3))
  Using cached PyAutoGUI-0.9.54-py3-none-any.whl
Collecting pillow (from -r requirements.txt (line 4))
  Using cached pillow-10.3.0-cp312-cp312-macosx_11_0_arm64.whl.metadata (9.2 kB)
Collecting pytest (from -r requirements.txt (line 5))
  Using cached pytest-8.2.1-py3-none-any.whl.metadata (7.6 kB)
Collecting autopy (from -r requirements.txt (line 6))
  Downloading autopy-4.0.0.tar.gz (20 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "/Volumes/K2TB/Work/Coding/Python/PedalboardHost/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Volumes/K2TB/Work/Coding/Python/PedalboardHost/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/Volumes/K2TB/Work/Coding/Python/PedalboardHost/.venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/xd/4fcz4tqj7xs58kz3z7fy18xc0000gp/T/pip-build-env-67wgcmos/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/private/var/folders/xd/4fcz4tqj7xs58kz3z7fy18xc0000gp/T/pip-build-env-67wgcmos/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/xd/4fcz4tqj7xs58kz3z7fy18xc0000gp/T/pip-build-env-67wgcmos/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/private/var/folders/xd/4fcz4tqj7xs58kz3z7fy18xc0000gp/T/pip-build-env-67wgcmos/overlay/lib/python3.12/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      ModuleNotFoundError: No module named 'setuptools_rust'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by pevogam** [comment]
Could you try this with a wheel for your platform among these build artifacts?

https://github.com/autopilot-rs/autopy/actions/runs/14040870872
